# -*- coding: utf-8 -*-
"""NBA-Stats-IC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yD2DbDxeiD1hqnwFIJfvJbGmXNCmkYf
"""

# PYTHON MODULES
# import user-installed modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# pandas options
pd.set_option('display.max_rows', 100)

!wget -nc 'https://raw.githubusercontent.com/hpestka10/ITP349_NBAStats_Pestka/refs/heads/main/nba_game_log_2021_22.csv'
nba_player_log = pd.read_csv('nba_game_log_2021_22.csv')

!wget -nc 'https://raw.githubusercontent.com/hpestka10/ITP349_NBAStats_Pestka/refs/heads/main/nba_salary_2021_22.csv'
player_salaries = pd.read_csv('nba_salary_2021_22.csv')

# view columns and null counts for each column in the data frames
print(nba_player_log.columns)
print(nba_player_log.info())
print(player_salaries.columns)
print(player_salaries.info())

# shape of the data frames

# player game log:
print("NBA player log shape:")
print(nba_player_log.shape)
# player salaries
print("NBA player Salaries")
print(player_salaries.shape)

# show first five rows of each data frame
# nba player log
print(nba_player_log.head())
print("\n")
# player salaries
print(player_salaries.head())

# clean player logs
top_scorer_df = nba_player_log[['game_id', 'game_date','H_A', 'Team_Abbrev','Opponent_Abbrev','player', 'pts','minutes']]
print(top_scorer_df.head())


print("Player log data: ")
print("Shape before dropping duplicates and unneeded columns: ")
print(nba_player_log.shape)


top_scorer_df = top_scorer_df.drop_duplicates()


print("Shape after dropping duplicates and unneeded columns: ")
print(top_scorer_df.shape)


# clean player salary data
top_salary_df = player_salaries[['Player',   '2021/22',   '2022/23',   '2023/24',   '2024/25',   '2025/26']]
print(top_salary_df.head())


print("Player salary data: ")
print("Shape before dropping duplicates and unneeded columns: ")
print(player_salaries.shape)


top_salary_df = top_salary_df.drop_duplicates()


print("Shape after dropping duplicates and unneeded columns: ")
print(top_salary_df.shape)

print(top_salary_df.head())
print(top_scorer_df.head())

# use pd.merge() to combine to two datasets, then clean the resulting data frame
player_stats_salaries = pd.merge(top_scorer_df,top_salary_df,how='left',left_on='player',right_on='Player')
print(player_stats_salaries.shape)
print(player_stats_salaries.info())

# drop null rows with null values
player_stats_salaries = player_stats_salaries.dropna(how='any')

 # rename columns
player_stats_salaries = player_stats_salaries.rename(columns={"2021/22":"Salary", "H_A":"Home_Away"})

print(player_stats_salaries.head())
print(player_stats_salaries.shape)