# -*- coding: utf-8 -*-
"""NBAStatsAndSalaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUIcHSQmc3KIMzFjb1jUAkYioSAoEv_c
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 100)

!wget -nc = 'https://raw.githubusercontent.com/hpestka10/ITP349_NBAStats_Pestka/refs/heads/main/nba_game_log_2021_22%20(1).csv'
!wget -nc = 'https://raw.githubusercontent.com/hpestka10/ITP349_NBAStats_Pestka/refs/heads/main/nba_salary_2021_22%20(1).csv'

RawStatsDF = pd.read_csv('nba_game_log_2021_22 (1).csv')
RawSalaryDF = pd.read_csv('nba_salary_2021_22 (1).csv')

StatsDF = RawStatsDF[['game_id',  'game_date',  'Team_Abbrev', 'player',  'pts', 'minutes', 'triple_double']]
StatsDF.head()

SalaryDF = RawSalaryDF[['Player',  '2021/22', '2022/23']]
SalaryDF.head()

print(StatsDF.isnull().sum())
print(SalaryDF.isnull().sum())
StatsDF.drop_duplicates()
SalaryDF.drop_duplicates()

print(StatsDF.shape)
print(SalaryDF.shape)
# No null or duplicate values

MergeDF = pd.merge(StatsDF, SalaryDF, how='left', left_on='player', right_on='Player')
print(MergeDF.shape)
MergeDF.head()

triple_double = MergeDF.groupby('Player')['triple_double'].sum().reset_index()
triple_double.columns = ['Player', 'Triple_Doubles']

plt.figure(figsize=(10, 6))
plt.bar(triple_double['Player'], triple_double['Triple_Doubles'], color='maroon')
plt.xlabel('Player')
plt.ylabel('Trile Double Count')
plt.title('Triple Double count')
plt.show()

print(triple_double.max())